const IMAGES = {
  kalahari2: require('../images/kalahari2.jpg'),
  kalahari3: require('../images/kalahari3.jpg'),
  perubanner: require('../images/perubanner.jpg'),
  southafricabanner: require('../images/southafricabanner.jpg'),
  egyptbanner: require('../images/egyptbanner.jpg'),
  botswanabanner: require('../images/botswanabanner.jpg'),
  namibiabanner: require('../images/namibiabanner.jpg'),
  tanzaniabanner: require('../images/tanzaniabanner.jpg'),
  kenyabanner: require('../images/kenyabanner.jpg'),
  indonesiabanner: require('../images/indonesiabanner.jpg'),
  japanbanner: require('../images/japanbanner.jpg'),
  malaysiabanner: require('../images/malaysiabanner.jpg'),
  thailandbanner: require('../images/thailandbanner.jpg'),
  nepalbanner: require('../images/nepalbanner.jpg'),
  philippinesbanner: require('../images/philippinesbanner.jpg'),
  cambodiabanner: require('../images/cambodiabanner.jpg'),
  ecuadorbanner: require('../images/ecuadorbanner.jpg'),
  galapagosbanner: require('../images/galapagosbanner.jpg'),
  boliviabanner: require('../images/boliviabanner.jpg'),
  italybanner: require('../images/italybanner.jpg'),
  maltabanner: require('../images/maltabanner.jpg'),
  boliviatop5llama: require('../images/boliviatop5llama.jpg'),
}

export default IMAGES;